# Generated by Django 3.1 on 2020-08-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayurvedicmedicines',
            name='image',
            field=models.ImageField(default='image-not-available.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='dailyessentials',
            name='image',
            field=models.ImageField(default='image-not-available.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='healthsupplements',
            name='image',
            field=models.ImageField(default='image-not-available.jpg', upload_to='products'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='image',
            field=models.ImageField(default='image-not-available.jpg', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='ayurvedicmedicines',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyessentials',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='healthsupplements',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
