# Generated by Django 3.1 on 2020-08-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200821_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayurvedic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ayurvedicmedicines')),
                ('essentials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dailyessentials')),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medicines')),
                ('supplements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.healthsupplements')),
            ],
        ),
    ]
